name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "[Bug]: "
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary checks
      options:
        - label: I have searched the existing issues to make sure this isn't a duplicate.
          required: true
        - label: I have read the documentation and tried the recommended troubleshooting steps.
          required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please paste any relevant logs. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information.
      placeholder: |
        OS: Windows/macOS/Linux
        Shell: bash/zsh/pwsh
        Version: x.y.z
        Installation method: e.g. Homebrew, npm, manual, etc.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
